- id: pylint-ignore
  name: pylint-ignore
  entry: pylint-ignore
  language: python
  types: [python]
  require_serial: true

- id: pylint-ignore-update
  name: update pylint-ignore file
  entry: pylint-ignore
  args: ["--update-ignorefile"]
  stages: [manual]
  language: python
  types: [python]
  require_serial: true
